name: 1Chrome

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading Resources...
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Invoke-WebRequest https://www.win-rar.com/fileadmin/winrar-versions/winrar/winrar-x64-611.exe -OutFile winrar.exe
          Invoke-WebRequest https://bits.avcdn.net/productfamily_CCLEANER/insttype_FREE/platform_WIN_PIR/installertype_ONLINE/build_RELEASE -OutFile ccsetup602.exe        
          Invoke-WebRequest https://raw.githubusercontent.com/FirmanNesatsumi/YouTubeNgrokRDP/main/resources/start.bat -OutFile start.bat
          Invoke-WebRequest https://raw.githubusercontent.com/FirmanNesatsumi/YouTubeNgrokRDP/main/resources/loop.bat -OutFile loop.bat
          Invoke-WebRequest https://raw.githubusercontent.com/FirmanNesatsumi/YouTubeNgrokRDP/main/resources/loop.ps1 -OutFile loop.ps1
          Invoke-WebRequest https://raw.githubusercontent.com/FirmanNesatsumi/YouTubeNgrokRDP/main/resources/1ChromeShortcuts.zip -OutFile 1ChromeShortcuts.zip
          Invoke-WebRequest https://raw.githubusercontent.com/FirmanNesatsumi/YouTubeNgrokRDP/main/resources/1ChromeProfiles.zip -OutFile 1ChromeProfiles.zip

      - name: Extracting Ngrok Files...
        run: Expand-Archive ngrok.zip

      - name: Connecting to your Ngrok Account...
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enabling RDP Access...
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          copy winrar.exe C:\Users\Public\Desktop\winrar.exe
          copy ccsetup602.exe C:\Users\Public\Desktop\ccsetup602.exe
          copy 1ChromeShortcuts.zip C:\Users\Public\Desktop\1ChromeShortcuts.zip
          copy 1ChromeProfiles.zip C:\Users\Public\Desktop\1ChromeProfiles.zip

      - name: Install Winrar...
        run: cmd /c C:\Users\Public\Desktop\winrar.exe winrar.exe /s

      - name: Install CCLeaner...
        run: cmd /c C:\Users\Public\Desktop\winrar.exe ccsetup602.exe /s

      - name: Extracting Chrome Shortcuts...
        run: Expand-Archive -LiteralPath 'C:\Users\Public\Desktop\1ChromeShortcuts.zip' -DestinationPath C:\Users\Public\Desktop\1ChromeShortcuts

      - name: Extracting Chrome Shortcuts...
        run: Expand-Archive -LiteralPath 'C:\Users\Public\Desktop\1ChromeProfiles.zip' -DestinationPath C:\Users\Public\Desktop\1ChromeProfiles

      - name: Creating Tunnel...
        run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

      - name: Connect To Your RDP [CPU 2 Core - 7GB Ram - 256 SSD - 1 Hour]
        run: cmd /c start.bat

      - name: RDP Started Successfully! Now you can close the tab.
        run: cmd /c loop.bat
